### ISSUE TITLE
Display an info message when the invitation code is not valid

### ISSUE THREAD

**Issue by programarivm** [chesslab/redux-chess#122]
If the invitation code is not valid, the **Enter invite code** dialog will just close without informing about what went wrong. This issue is a usability improvement similar to https://github.com/programarivm/redux-chess/issues/116

![figure-01](https://user-images.githubusercontent.com/4062000/132673480-ce73da8b-4a75-41c4-8af3-28e69ab7a98d.png)

**Comment by programarivm** [comment]
@CTZxVULKAN what are your thoughts about this issue? Thank you!

**Comment by CTZxVULKAN** [comment]
Not a PHP genius but i think it can be easily be resolved just need to check if the code exists 
This is what i can tell from my  javascript experience :

```
// create a function to check if code exists
export const getRandom = async (req, res) => {
  try {

    // if everything is fine and code exists do what we need to then 

    res.status(200).json(some message);

  } catch (error) {

    // if theres an error return a message or create an alert popup saying code doesnt exist
    res.status(404).json({message: error.message});
  }
};
```
Could you tell me which file is responsible for this ?
Very new at php but i will try to resolve this tomorrow .

**Comment by CTZxVULKAN** [comment]
Ohh i just realised that this uses js makes things easier for me.
Could you tell me which files are responsible and also how to setup a testing enviorment ( i know the js frontend but i need to know about the php backend) will be a great help then :)

**Comment by programarivm** [comment]
Thanks for the help @CTZxVULKAN it's very much appreciated! 

There's a list of tutorials in the README, hopefully this one should help to set up the testing environment:

- [How to Test a Local React NPM Package With Ease](https://javascript.plainenglish.io/testing-a-local-react-npm-package-with-ease-7d0668676ddb)

**Comment by CTZxVULKAN** [comment]
Thanks i will look into them .
I cant gaurantee a fix as i am having exams now and wont be able to work all that much but will try my best to help.

:)

**Comment by CTZxVULKAN** [comment]
@programarivm I am having a bit trouble with the code base here .
I have gone through `CreateInviteCodeDialog.js` & `EnterInviteCodeDialog.js` & all corrosponding `actions` & `reducers`.
I would like to how how you validate the invite code and store it ( i have to to a check for the code being valid so i need that).

Also i am having issues setting up the testing enviorment.

Could you probably tell me in a simplified form how to setup the backend and frontend servers locally ?

There is **no** start script for the frontend and i am getting errors while setting up the backend when running `php ws-server.php`
Error : 
```
PHP Warning:  require(/home/vulkan/git/chess-server/cli/../vendor/autoload.php): Failed to open stream: No such file or directory in /home/vulkan/git/chess-server/cli/ws-server.php on line 10
PHP Fatal error:  Uncaught Error: Failed opening required '/home/vulkan/git/chess-server/cli/../vendor/autoload.php' (include_path='.:') in /home/vulkan/git/chess-server/cli/ws-server.php:10
Stack trace:
#0 {main}
  thrown in /home/vulkan/git/chess-server/cli/ws-server.php on line 10
```
I am still very new to this and i would really appreciate if you were to help me out in this. I am super hyped about working on this project with you.

**Comment by programarivm** [comment]
Well, the project is quite challenging in reality, probably the first thing to do is set up a local testing environment.

You may want to have a look at the following two repos:

- [Redux Chess Demo](https://github.com/programarivm/demo-redux-chess)
- [Redux Chess Testing Environment](https://github.com/programarivm/testing-redux-chess)

Please let me know your thoughts, thank you!

**Comment by programarivm** [comment]
These are the start scripts for the frontend, which are to be run on the `testing-redux-chess` app:

```
$ npm start
```

```
$ npm run publish:npm --prefix /home/standard/projects/redux-chess && npm run update:local:redux-chess && npm run restart --port=3000
```

**Comment by programarivm** [comment]
@CTZxVULKAN could you run the app locally? 

BTW, the local PHP server is not actually necessary because there's a staging server up and running too. 

The chessboard can be initialized as it is described next:

```
import React from 'react';
import ReactDOM from 'react-dom';
import { Chess } from 'redux-chess';

const props = {
  server: {
    prot: 'wss',
    host: 'pchess.net',
    port: '8443'
  }
};

ReactDOM.render(
  <Chess props={props} />,
  document.getElementById('redux-chess')
);
```
So, this issue involves React and JS.

Redux DevTools should be installed in your browser.

**Comment by CTZxVULKAN** [comment]
I am sorry i was a bit busy yesterday i will look into this soon

**Comment by programarivm** [comment]
Thank you! This issue may not be too obvious if this is the first time you're working with React, so I'd recommend to take it easy. Remember, the secret to writing code [with ease and joy](https://javascript.plainenglish.io/my-first-integration-test-in-a-redux-hooked-app-3b189addd46e) is take one step at a time. I'll be looking at this one as well if this makes any sense.

**Comment by programarivm** [comment]
Merged PR https://github.com/chesslab/redux-chess/pull/126
